name: Security - OWASP ZAP

on:
  workflow_dispatch:

jobs:
  zap-baseline:
    name: OWASP ZAP Baseline - DEV
    runs-on: ubuntu-latest

    steps:
      - name: Ejecutar ZAP Baseline
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: 'https://stunning-truth-dev.up.railway.app'
          allow_issue_writing: false